FROM php:8.2-fpm

# Copy composer.lock and composer.json
# COPY composer.lock composer.json /var/www/


RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    jpegoptim optipng pngquant gifsicle \
    vim \
    git   \
    curl  \
    zip \
    unzip \
    libpq-dev \
    libzip-dev \
    libexif-dev \
    libonig-dev 

WORKDIR /var/www

# Clear cache (limpa o cache após a instalação)
RUN apt-get clean && rm -rf /var/lib/apt/lists/*


# Install extensions (dependências do php, postgres)
RUN docker-php-ext-install pdo pdo_pgsql mbstring zip exif pcntl
RUN docker-php-ext-install gd

# Install composer (gerenciador de pacotes do laravel)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application (usuário da aplicação do laravel)
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents (copiando a pasta que está o arquivo, tudo para /var/www)
COPY . /var/www

# Copy existing application directory permissions (aplicando permissões do diretório)
COPY --chown=www:www . /var/www

# Ajuste de permissões
RUN chown -R www-data:www-data /var/www/application
RUN chmod -R 777 /var/www/application

# Change current user to www (alteração do usuário para o usuário www)
USER www

# Expose port 9000 and start php-fpm server (porta do container)
EXPOSE 9000
#comando para execução da imagem do php
CMD ["php-fpm"] 